volumes:
  hs_database:

services:

  mariadb_test:
    build:
      context : ./database
      dockerfile : Dockerfile
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - DB_NAME=hs_db_test
      - DB_USER=hs_user
      - DB_PASSWORD=hs_test!
    volumes:
      - hs_database:/var/lib/mysql
    networks:
      - storage_network
    ports:
      - "9000:3306"
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      start_period: 15s
      interval: 10s
      timeout: 5s
      retries: 3

  api:
    container_name: api
    build:
      context: ./back
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      DB_URL: mysql://mariadb_test:3306/hs_db_test
      DB_USER: hs_user
      DB_PASSWORD: hs_test!
    networks:
      - storage_network
    depends_on:
      mariadb_test:
        condition: service_healthy

networks:
  storage_network:

#  front:
#    build: ./front/.dockerfile
#    ports:
#      - "7000:5173"
# sudo docker run --detach --name mariadb_test -v hs_database:/var/lib/mysql --env MARIADB_ROOT_PASSWORD=root -p 9000:3306 mariadb:latest